apiVersion: v1
kind: Service
metadata:
  name: recipe-db
  namespace: recipeapp
spec:
  clusterIP: None
  selector:
    app: recipe-db
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: recipe-db
  namespace: recipeapp
spec:
  serviceName: recipe-db
  replicas: 1
  selector:
    matchLabels:
      app: recipe-db
  template:
    metadata:
      labels:
        app: recipe-db
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: recipeapp_db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: recipe-service-secret
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: recipe-service-secret
                  key: DB_PASSWORD
          volumeMounts:
            - name: recipe-db-storage
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres"]
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
  volumeClaimTemplates:
    - metadata:
        name: recipe-db-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
