# Generated by Django 4.2.27 on 2026-02-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ABTestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True, help_text="The user's ID (from recipe service)")),
                ('test_name', models.CharField(db_index=True, help_text='Name of the A/B test', max_length=100)),
                ('variant_id', models.CharField(help_text='The variant the user was assigned to', max_length=50)),
                ('event_type', models.CharField(db_index=True, help_text="Type of event: 'impression' or custom event name", max_length=100)),
                ('path', models.CharField(blank=True, help_text='URL path where the event occurred', max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional event metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this event occurred')),
            ],
            options={
                'indexes': [models.Index(fields=['test_name', 'event_type', 'created_at'], name='analytics_a_test_na_9e505b_idx'), models.Index(fields=['user_id', 'test_name', 'event_type'], name='analytics_a_user_id_91f092_idx')],
            },
        ),
        migrations.CreateModel(
            name='ABTestAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True, help_text="The authenticated user's ID (from recipe service)")),
                ('test_name', models.CharField(db_index=True, help_text='Name of the A/B test (matches tests.json)', max_length=100)),
                ('variant_id', models.CharField(help_text='The variant ID assigned to this user', max_length=50)),
                ('assigned_at', models.DateTimeField(auto_now_add=True, help_text='When this assignment was created')),
            ],
            options={
                'indexes': [models.Index(fields=['test_name', 'variant_id'], name='analytics_a_test_na_b04419_idx')],
                'unique_together': {('user_id', 'test_name')},
            },
        ),
    ]
