apiVersion: v1
kind: Secret
metadata:
  name: analytics-service-secret
  namespace: recipeapp
type: Opaque
stringData:
  SECRET_KEY: "change-me-to-a-real-secret-key"
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"
  INTERNAL_SERVICE_KEY: "change-me-to-a-real-service-key"
