# Generated by Django 4.2.27 on 2026-04-07 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApproachELO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=50)),
                ('approach', models.CharField(max_length=50)),
                ('rating', models.IntegerField(default=1000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('feature', 'approach')},
            },
        ),
        migrations.CreateModel(
            name='DescriptionPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_approach', models.CharField(choices=[('casual', 'Casual'), ('professional', 'Professional'), ('poetic', 'Poetic')], max_length=20)),
                ('rejected_approach', models.CharField(choices=[('casual', 'Casual'), ('professional', 'Professional'), ('poetic', 'Poetic')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description_preferences', to='recipes.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'recipe')},
            },
        ),
    ]
